services:
  nas-organizer:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/Tamas/Documents/Inbox:/data/inbox"
      - "C:/Users/Tamas/Documents/Archive:/data/archive"
      - "./rules.yaml:/app/rules.yaml"
      - "./logs:/app/logs"
      - "./templates:/app/templates"
      - "./schemas:/app/schemas"
      - "./cache.db:/data/cache.db"
      - "./ml:/data/ml"                # << new folder for models
    environment:
      - CACHE_DB=/data/cache.db
      - MODEL_PATH=/data/ml/model.pkl  # << point to folder file
      - ARCHIVE_ROOT=/data/archive
      - ML_MODE=HYBRID
      - ML_THRESHOLD=0.75